### PR TITLE
Update jsSHA library from version 1.6.0 to 2.3.1. 

### PR DESCRIPTION
**Pull request by adaxi**
Branch 1.X is no longer updated.

### CODE REVIEW

**Comment by dylmye** [comment]
Doesn't look like this repo is maintained anymore

**Comment by adaxi** [comment]
You are willing to fork and maintain it?

**Comment by dylmye** [comment]
Hiya - I wouldn't be able to do a good job due to commitments, sorry

**Comment by adaxi** [comment]
Same here ...

**Comment by ognus** [comment]
Hi, I am willing to resurrect the project and maintain it. Sorry for delayed response, due to my mistake I have stopped receiving notifications from Github for a while.

**Comment by adaxi** [comment]
No worries. I think if you come by from time to time it should be enough to manage this project. Thank you for your time.

**Comment by dylmye** [comment]
+1, thank you ognus.

**Comment by ognus** [comment]
@adaxi @dylmye new release (0.1.2) published to NPM, thank you.

**Pull request merged**
