### PR TITLE
add neogas

### PR DESCRIPTION
**Pull request by iddoberger**
Neo Gas has a current market cap of ~200M$

### CODE REVIEW

**Comment by ognus** [comment]
@iddoberger thank, you. Appreciate the PR, do you have an idea why the test doesn't pass? Are all GAS addresses follow the same format as NEO address?

**Comment by iddoberger** [comment]
Thanks, I think your project has much value. Yes, they are the same format: https://www.reddit.com/r/NEO/comments/6tp24r/gas_address_the_same_as_the_neo_address/?st=jg51ha8z&sh=473f7d1f. Strange that the test did not pass, I will try to have a close look at it later today

**Comment by iddoberger** [comment]
@ognus Fixed it:)

**Comment by ognus** [comment]
awesome @iddoberger 👍 will merge using console to resolve conflicts, thank you :)

**Comment by ognus** [comment]
Merged to master using console, closing.

**Pull request closed without merging**
