### PR TITLE
Extended currencies list with Decred

### PR DESCRIPTION
**Pull request by R3VoLuT1OneR**
Hey,

Please review my MR.

### CODE REVIEW

**Comment by ognus** [comment]
@R3VoLuT1OneR thank you, it looks very good. Appreciate the PR, just have one question, if I may. Have you considered using pure JS Blake's implementation https://github.com/dcposch/blakejs vs the wrapper (https://github.com/cryptocoinjs/blake-hash)? Was performance a consideration?

**Comment by R3VoLuT1OneR** [comment]
@ognus I actually did't see the "blakejs". I will try this one, because blake-hash mostly for node.

**Comment by R3VoLuT1OneR** [comment]
@ognus Checked the package, it is not doing what needed.
It is not BLAKE256, but some other with less hash rounds.

**Comment by ognus** [comment]
@R3VoLuT1OneR right, sorry. Blake2s is indeed incompatible with Blake256 that Decred needs.

**Pull request merged**
