### PR TITLE
Add some equihash coins

### PR DESCRIPTION
**Pull request by hellcatz**

### CODE REVIEW

**Comment by ognus** [comment]
@hellcatz thanks a lot for the PR :) Do you plan to add some tests for the bunch of coins you've added, please let me know. If not I will try to add them later 👍

**Comment by hellcatz** [comment]
I'll look into adding addresses for these coins to the tests. :+1:

**Comment by hellcatz** [comment]
Updated browser files, tests now passing.
For invalid test, I modified 1 character in a valid address and perform the commonTests
@ognus Please check, looks like all tests are now passing 👍

**Comment by ognus** [comment]
@hellcatz amazing work 🥇 thank you 👍

**Pull request merged**
